const SearchActionTypes = {
    FETCH_RESULT: 'FETCH_RESULT',
    FETCH_RESULT_SUCCESS: 'FETCH_RESULT_SUCCESS',
    FETCH_RESULT_FAILURE: 'FETCH_RESULT_FAILURE',
    ADD_SEARCH_HISTORY: 'ADD_SEARCH_HISTORY',
    CLEAR_SEARCH_HISTORY: 'CLEAR_SEARCH_HISTORY',
    ADD_SEARCH_ID: 'ADD_SEARCH_ID',
    ADD_SEARCH_QUERY: 'ADD_SEARCH_QUERY',
    TOGGLE_INLINE_SEARCH: 'TOGGLE_INLINE_SEARCH',

};

export default SearchActionTypes;